name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Upgrade pip
      run: pip install --upgrade pip
    
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Python Program
      run: python ConvertMD.py

      
